---
 - name: register zpools
   command: 'zpool list -H'
   register: zfs_existing_pools
   changed_when: false
   failed_when: false

 - name: create zpools
   command: 'zpool create {{ item.key }} raidz {{ item.value.devices }}'
   with_dict: '{{ zfs_zpools }}'
   when: item.key not in zfs_existing_pools.stdout

 - name: create zvols
   zfs:
     name: '{{ item.value.pool }}/{{ item.key }}'
     snapdir: '{{ item.value.snapdir | default("hidden") }}'
     snapdev: '{{ item.value.snapdev | default("hidden") }}'
     volsize: '{{ item.value.volsize | default(omit) }}'
     compression: '{{ item.value.compression | default("none") }}'
     sync: '{{ item.value.sync | default("standard") }}'
     mountpoint: '{{ item.value.mountpoint | default(omit) }}'
     state: '{{ item.value.state | default("present") }}'
   with_dict: '{{ zfs_zvols }}'  

