---
 - name: register zpools
   command: 'zpool list -H'
   register: zfs_existing_pools
   changed_when: false
   failed_when: false

 - name: create zpools
   command: 'zpool create {{ item.key }} {{ item.value.devices }}'
   with_dict: '{{ zfs_zpools }}'
   when: item.key not in zfs_existing_pools.stdout
