---
 - name: register zpools
   command: 'zpool list -H'
   register: zfs_existing_pools
   changed_when: false
   failed_when: false

 - name: create zpools
   command: 'zpool create {{ item.key }} {{ item.value.raidmode | default() }} {{ item.value.devices }}'
   with_dict: '{{ zfs_zpools }}'
   when:
     - item.key not in zfs_existing_pools.stdout
     - zfs_zpools is defined

 - name: create log for zpool
   command: 'zpool add -f {{ item.key }} log {{ item.value.zildevices }}'
   with_dict: '{{ zfs_zpools }}'
   when:
     - item.key not in zfs_existing_pools.stdout
     - zfs_zpools is defined
     - item.value.zildevices is defined

 - name: create cache for zpool
   command: 'zpool add -f {{ item.key }} cache {{ item.value.cachedevices }}'
   with_dict: '{{ zfs_zpools }}'
   when:
     - item.key not in zfs_existing_pools.stdout
     - zfs_zpools is defined
     - item.value.cachedevices is defined

 - name: create zvols
   zfs:
     name: '{{ item.value.pool }}/{{ item.key }}'
     snapdir: '{{ item.value.snapdir | default("hidden") }}'
     snapdev: '{{ item.value.snapdev | default("hidden") }}'
     volsize: '{{ item.value.volsize | default(omit) }}'
     compression: '{{ item.value.compression | default("off") }}'
     sync: '{{ item.value.sync | default("standard") }}'
     mountpoint: '{{ item.value.mountpoint | default(omit) }}'
     state: '{{ item.value.state | default("present") }}'
     acltype: 'posixacl'
   with_dict: '{{ zfs_zvols }}'
   when:
     - zfs_zvols is defined
