---
 - name: install kernel headers for current kernel
   package:
     name: "{{ zfs_kernel_package_prefix }}{{ ansible_kernel }}"


 - name: install zfs dkms
   apt:
     name: '{{ zfs_packages }}'
     default_release: '{{ ansible_distribution_release }}-backports'
   when: 
    - ansible_distribution == 'Debian'
    - ansible_distribution_major_version < "10"

 - name: install zfs dkms
   apt:
     name: '{{ zfs_packages }}'
   when: 
    - ansible_distribution == 'Debian'
    - ansible_distribution_major_version >= "10"

 - name: install zfs dkms
   package:
     name: '{{ item }}'
   with_list: '{{ zfs_packages }}'

 - name: ensure zfs module is loaded
   modprobe:
     name: '{{ zfs_module_name }}'
